Resources:
  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "ticketId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "ticketId"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "Tickets"